# Generated by Django 3.2.9 on 2022-05-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20220520_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Город, область ', 'verbose_name_plural': 'Область '},
        ),
    ]
