# Generated by Django 3.2.9 on 2022-05-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Город, область ', 'verbose_name_plural': 'Кыргызстан '},
        ),
    ]
