# Generated by Django 3.2.9 on 2022-05-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mincategory',
            options={'verbose_name': 'Районы', 'verbose_name_plural': 'Район'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Область, город', 'verbose_name_plural': 'Город'},
        ),
    ]
