# Generated by Django 3.2.9 on 2022-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20220520_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mincategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
