# Generated by Django 3.2.9 on 2022-05-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('pin', models.CharField(max_length=255, unique=True, verbose_name='ПИН')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('erp', models.TextField(verbose_name='Номер ЕРП')),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='Прикрепить файл')),
                ('image1', models.ImageField(null=True, upload_to='media', verbose_name='Копия паспорта')),
                ('image2', models.ImageField(null=True, upload_to='media', verbose_name='Вставить файл')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Добавить',
                'verbose_name_plural': 'Добавить данные',
                'ordering': ['-created'],
            },
        ),
    ]
