# Generated by Django 3.2.9 on 2022-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='pin_bank',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Номер карточки'),
        ),
        migrations.AddField(
            model_name='db',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='db',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
