# Generated by Django 3.2.9 on 2022-05-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20220517_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='pin_bank',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Номер карточки банка'),
        ),
    ]
