# Generated by Django 3.2.9 on 2022-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20220517_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='image',
            field=models.FileField(null=True, upload_to='media', verbose_name='Прикрепить файл'),
        ),
        migrations.AlterField(
            model_name='db',
            name='image1',
            field=models.FileField(null=True, upload_to='media', verbose_name='Копия паспорта'),
        ),
        migrations.AlterField(
            model_name='db',
            name='image2',
            field=models.FileField(null=True, upload_to='media', verbose_name='Вставить файл'),
        ),
    ]
