# Generated by Django 3.2.9 on 2022-05-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20220520_1536'),
        ('db', '0010_auto_20220520_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.category', verbose_name='Выберите область'),
        ),
        migrations.AlterField(
            model_name='db',
            name='mincategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.mincategory', verbose_name='Выберите '),
        ),
        migrations.AlterField(
            model_name='db',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.subcategory', verbose_name='Выберите город'),
        ),
    ]
